const appActionTypes = {
    TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
    UPDATE_SIDEBAR_TYPE: "UPDATE_SIDEBAR_TYPE",
    SIDEBAR_TYPES: {
        CONTACT: "CONTACT",
        SHARED_MESSAGES: "SHARED_MESSAGES",
        STARRED_MESSAGES: "STARRED_MESSAGES"
    },
    TOGGLE_DIALOG: "TOGGLE_DIALOG",
    TOGGLE_SHORTCUT_DIALOG: "TOGGLE_SHORTCUT_DIALOG",
    TOGGLE_THEME_DIALOG: "TOGGLE_THEME_DIALOG"
}

export default appActionTypes