const appActionTypes = {
    TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
    UPDATE_SIDEBAR_TYPE: "UPDATE_SIDEBAR_TYPE",
    SIDEBAR_TYPES: {
        CONTACT: "CONTACT",
        SHARED_MESSAGES: "SHARED_MESSAGES",
        STARRED_MESSAGES: "STARRED_MESSAGES"
    }
}

export default appActionTypes