const userActionTypes = {
    GET_FRIENDS_REQUEST: "",
    GET_FRIENDS_SUCCESS: "GET_FRIENDS_SUCCESS",
    GET_FRIENDS_FAILURE: "GET_FRIENDS_FAILURE",
    GET_FRIEND_REQUESTS: "GET_FRIEND_REQUESTS",
    GET_FRIEND_REQUESTS_SUCCESS: "GET_FRIEND_REQUESTS_SUCCESS",
    GET_FRIEND_REQUESTS_FAILURE: "GET_FRIEND_REQUESTS_FAILURE",
    GET_USERS_REQUEST: "GET_USERS_REQUEST",
    GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
    GET_USERS_ERROR: "GET_USERS_ERROR",

}

export default userActionTypes