const userActionTypes = {
    GET_FRIENDS_REQUEST: "GET_FRIENDS_REQUEST",
    GET_FRIENDS_SUCCESS: "GET_FRIENDS_SUCCESS",
    GET_FRIENDS_FAILURE: "GET_FRIENDS_FAILURE",
    GET_FRIEND_REQUESTS_REQUEST: "GET_FRIEND_REQUESTS_REQUEST",
    GET_FRIEND_REQUESTS_SUCCESS: "GET_FRIEND_REQUESTS_SUCCESS",
    GET_FRIEND_REQUESTS_FAILURE: "GET_FRIEND_REQUESTS_FAILURE",
    GET_USERS_REQUEST: "GET_USERS_REQUEST",
    GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
    GET_USERS_FAILURE: "GET_USERS_FAILURE",
    GET_USER_REQUEST: "GET_USER_REQUEST",
    GET_USER_SUCCESS: "GET_USER_SUCCESS",
    GET_USER_FAILURE: "GET_USER_FAILURE",
    SEARCH_USERS_REQUEST: "SEARCH_USERS_REQUEST",
    SEARCH_USERS_SUCCESS: "SEARCH_USERS_SUCCESS",
    SEARCH_USERS_FAILURE: "SEARCH_USERS_FAILURE",
    RESET: "RESET"
}

export default userActionTypes